
import type { MenuCategory } from './types';

export const filterCategories: string[] = [
  'Main Course',
  'Snacks',
  'Salad and Seafood',
  'Khmer Food',
  'Soup',
  'Noodles',
  'Soft Drinks',
  'Desserts',
  'Beverages'
];

export const menuData: MenuCategory[] = [
  {
    title: 'Appetizers',
    items: [
      {
        id: 'APP001',
        name: 'Spring Rolls',
        description: 'Crispy vegetable spring rolls served with a sweet chili dipping sauce.',
        price: 5.99,
        originalPrice: 7.99,
        image: 'https://picsum.photos/seed/springrolls/400/400',
        images: ['https://picsum.photos/seed/springrolls/800/600', 'https://picsum.photos/seed/springrolls-thumb1/100/100', 'https://picsum.photos/seed/springrolls-thumb2/100/100'],
        category: 'Snacks',
      },
      {
        id: 'APP002',
        name: 'Chicken Wings',
        description: 'Spicy buffalo wings with a side of blue cheese dressing.',
        price: 8.99,
        image: 'https://picsum.photos/seed/chickenwings/400/400',
        images: ['https://picsum.photos/seed/chickenwings/800/600', 'https://picsum.photos/seed/chickenwings-thumb1/100/100', 'https://picsum.photos/seed/chickenwings-thumb2/100/100'],
        category: 'Snacks',
        isHot: true,
      },
      {
        id: 'APP003',
        name: 'Soup of the Day',
        description: "Chef's special soup, made with the freshest seasonal ingredients.",
        price: 4.99,
        image: 'https://picsum.photos/seed/soup/400/400',
        images: ['https://picsum.photos/seed/soup/800/600', 'https://picsum.photos/seed/soup-thumb1/100/100', 'https://picsum.photos/seed/soup-thumb2/100/100'],
        category: 'Soup',
      },
    ],
  },
  {
    title: 'Main Course',
    items: [
      {
        id: 'MAIN001',
        name: 'Fried Rice',
        description: 'Classic fried rice with chicken, beef, or tofu and mixed vegetables.',
        price: 5.99,
        originalPrice: 8.99,
        image: 'https://picsum.photos/seed/friedrice/400/400',
        images: ['https://picsum.photos/seed/friedrice/800/600', 'https://picsum.photos/seed/friedrice-thumb1/100/100', 'https://picsum.photos/seed/friedrice-thumb2/100/100'],
        category: 'Main Course',
      },
      {
        id: 'MAIN002',
        name: 'Margherita Pizza',
        description: 'Delicious pizza with fresh mozzarella, tomatoes, and basil.',
        price: 12.99,
        originalPrice: 15.99,
        image: 'https://picsum.photos/seed/pizza/400/400',
        images: ['https://picsum.photos/seed/pizza/800/600', 'https://picsum.photos/seed/pizza-thumb1/100/100', 'https://picsum.photos/seed/pizza-thumb2/100/100'],
        category: 'Main Course',
      },
      {
        id: 'MAIN003',
        name: 'Beef Curry',
        description: 'Spicy beef curry with coconut milk, potatoes, and carrots.',
        price: 10.99,
        originalPrice: 14.99,
        image: 'https://picsum.photos/seed/beefcurry/400/400',
        images: ['https://picsum.photos/seed/beefcurry/800/600', 'https://picsum.photos/seed/beefcurry-thumb1/100/100', 'https://picsum.photos/seed/beefcurry-thumb2/100/100'],
        category: 'Khmer Food',
        isHot: true,
      },
      {
        id: 'MAIN004',
        name: 'Bibimbap',
        description: 'A traditional Korean mixed rice bowl with seasoned vegetables and gochujang.',
        price: 13.99,
        originalPrice: 18.99,
        image: 'https://picsum.photos/seed/bibimbap/400/400',
        images: ['https://picsum.photos/seed/bibimbap/800/600', 'https://picsum.photos/seed/bibimbap-thumb1/100/100', 'https://picsum.photos/seed/bibimbap-thumb2/100/100'],
        category: 'Main Course',
      },
       {
        id: 'MAIN005',
        name: 'Steamed Seabass with Soya Sauce',
        description: 'Delicate steamed seabass in a light and savory soya sauce.',
        price: 8.00,
        originalPrice: 10.00,
        image: 'https://picsum.photos/seed/seabass/400/400',
        images: ['https://picsum.photos/seed/seabass/800/600', 'https://picsum.photos/seed/seabass-thumb1/100/100', 'https://picsum.photos/seed/seabass-thumb2/100/100'],
        category: 'Salad and Seafood',
      },
    ],
  },
  {
    title: 'Desserts',
    items: [
      {
        id: 'DES001',
        name: 'Chocolate Cake',
        description: 'A rich and decadent chocolate layer cake with a smooth ganache frosting.',
        price: 6.99,
        image: 'https://picsum.photos/seed/chococake/400/400',
        images: ['https://picsum.photos/seed/chococake/800/600', 'https://picsum.photos/seed/chococake-thumb1/100/100', 'https://picsum.photos/seed/chococake-thumb2/100/100'],
        category: 'Desserts',
      },
      {
        id: 'DES002',
        name: 'Ice Cream Sundae',
        description: 'Classic vanilla ice cream with your choice of chocolate or caramel toppings.',
        price: 5.99,
        image: 'https://picsum.photos/seed/sundae/400/400',
        images: ['https://picsum.photos/seed/sundae/800/600', 'https://picsum.photos/seed/sundae-thumb1/100/100', 'https://picsum.photos/seed/sundae-thumb2/100/100'],
        category: 'Desserts',
      },
      {
        id: 'DES003',
        name: 'Fruit Tart',
        description: 'A beautiful tart with a crisp pastry cream, topped with fresh seasonal fruits.',
        price: 7.99,
        originalPrice: 9.99,
        image: 'https://picsum.photos/seed/fruittart/400/400',
        images: ['https://picsum.photos/seed/fruittart/800/600', 'https://picsum.photos/seed/fruittart-thumb1/100/100', 'https://picsum.photos/seed/fruittart-thumb2/100/100'],
        category: 'Desserts',
      },
    ],
  },
  {
    title: 'Beverages',
    items: [
      {
        id: 'BEV001',
        name: 'Fresh Orange Juice',
        description: '100% freshly squeezed orange juice, packed with vitamin C.',
        price: 3.99,
        image: 'https://picsum.photos/seed/orangejuice/400/400',
        images: ['https://picsum.photos/seed/orangejuice/800/600', 'https://picsum.photos/seed/orangejuice-thumb1/100/100', 'https://picsum.photos/seed/orangejuice-thumb2/100/100'],
        category: 'Beverages',
      },
      {
        id: 'BEV002',
        name: 'Iced Coffee',
        description: 'Smooth and refreshing cold brew coffee, served over ice.',
        price: 4.99,
        image: 'https://picsum.photos/seed/icedcoffee/400/400',
        images: ['https://picsum.photos/seed/icedcoffee/800/600', 'https://picsum.photos/seed/icedcoffee-thumb1/100/100', 'https://picsum.photos/seed/icedcoffee-thumb2/100/100'],
        category: 'Beverages',
      },
       {
        id: 'BEV003',
        name: 'Soda',
        description: 'Choose from a selection of classic sodas: Coke, Sprite, or Fanta.',
        price: 1.99,
        image: 'https://picsum.photos/seed/soda/400/400',
        images: ['https://picsum.photos/seed/soda/800/600', 'https://picsum.photos/seed/soda-thumb1/100/100', 'https://picsum.photos/seed/soda-thumb2/100/100'],
        category: 'Soft Drinks',
      },
    ],
  },
];
